In [7]:
# Setup the Jupyter version of Dash
from jupyter_dash import JupyterDash

# Configure the necessary Python module imports
import dash_leaflet as dl
from dash import dcc
from dash import html
import plotly.express as px
from dash import dash_table
from dash.dependencies import Input, Output
import base64

# Configure the plotting routines
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



# change animal_shelter and AnimalShelter to match your CRUD Python module file name and class name
from animal_shelter import AnimalShelter


###########################
# Data Manipulation / Model
###########################
username = "aacUser"
password = "SNHU1234"
shelter = AnimalShelter(username,password)

#create the dataframe
df = pd.DataFrame.from_records(shelter.read_all({}))





 
print(df)

app = JupyterDash(__name__)

image_filename = 'Grazioso Salvare Logo.png' # Upload company's logo image
encoded_image = base64.b64encode(open(image_filename, 'rb').read())


app.layout = html.Div([
    html.Div(id='hidden-div', style={'display':'none'}),
    html.Center(html.B(html.H1('AAC Shelter Animals'))),
    html.Center(html.B(html.H3('Jessica Duft-SNHU'))),
    html.Img(id='customer-image',src='data:image/png;base64,{}'.format(encoded_image.decode()),alt='customer image'),
    
    html.Hr(),
    html.Div(
        
        # Code for the interactive filtering options (radio buttons)
        dcc.RadioItems(
            id='filter-type',
            options=[
                {'label': 'Reset', 'value': 'RESET'},
                {'label': 'Water Rescue', 'value': 'WATER'},
                {'label': 'Mountain or Wilderness Rescue', 'value': 'MOUNTAIN OR WILDERNESS'},
                {'label': 'Disaster or Individual Tracking', 'value': 'DISASTER OR INDIVIDUAL TRACKING'}
            ]
        )

    ),
   
    dash_table.DataTable(id='datatable-id',
                         columns=[{"name": i, "id": i, "deletable": False, "selectable": True}
                                  for i in df.columns],
                         data=df.to_dict('records'),
                         editable=True,
                         filter_action="native",
                         sort_action="native",
                         sort_mode="multi",
                         column_selectable=False,
                         row_selectable="single",#allow a row to be selected
                         row_deletable=False,
                         selected_columns=[],
                         selected_rows=[],
                         page_action="native",
                         page_current=0,
                         page_size=10 #how many rows per page 
                         ),
     html.Br(),
     html.Hr(),
    
    
    #Display the chart on the left and the map on the right 
    html.Div(className='row',
         style={'display' : 'flex'},
             children=[
        html.Div(
            id='graph-id',
            className='col s12 m6',

            ),
        html.Div(
            id='map-id',
            className='col s12 m6',
            )
        ])
])



#############################################
# Interaction Between Components / Controller
#############################################
@app.callback([Output('datatable-id','data'),
               Output('datatable-id','columns'),
               Output('datatable-id','selected_rows')],
              [Input('filter-type', 'value')])
def update_dashboard(filter_type):
    # Code to filter interactive data table with MongoDB queries
    if filter_type == 'RESET':
        df = pd.DataFrame.from_records(shelter.read_all({}))
    elif filter_type == 'WATER':
        df = pd.DataFrame(list(shelter.read_all({
            "animal_type":"Dog",
            "breed":{"$in":["Labrador Retriever Mix", "Chesapeake Bay Retriever", "Newfoundland"]},
            "sex_upon_outcome":"Intact Female",
            "age_upon_outcome_in_weeks":{"$gte": 26},
            "age_upon_outcome_in_weeks":{"$lte": 156},
            "outcome_type":{"$nin":["Euthanasia"]}
        })))
    elif filter_type == 'MOUNTAIN OR WILDERNESS':
        df = pd.DataFrame(list(shelter.read_all({
            "animal_type":"Dog",
            "breed":{"$in":["German Shepherd", "Alaskan Malamute", "Old English Sheepdog", 
                          "Siberian Husky", "Rottweiler"]},
            "sex_upon_outcome":"Intact Male",
            "age_upon_outcome_in_weeks":{"$gte": 26},
            "age_upon_outcome_in_weeks":{"$lte": 156},
            "outcome_type":{"$nin":["Euthanasia"]}
        })))
    elif filter_type == 'DISASTER OR INDIVIDUAL TRACKING':
        df = pd.DataFrame(list(shelter.read_all({
            "animal_type":"Dog",
            "breed":{"$in":["Doberman Pinscher", "German Shepherd", "Golden Retriever", 
                          "Bloodhound", "Rottweiler"]},
            "sex_upon_outcome":"Intact Male",
            "age_upon_outcome_in_weeks":{"$gte": 20},
            "age_upon_outcome_in_weeks":{"$lte": 300},
            "outcome_type":{"$nin":["Euthanasia"]}
        })))
    
    else:
        df = pd.DataFrame.from_records(shelter.read_all({}))
        
    # Prepare data and columns to be sent to data table
    data=df.to_dict('records')
    columns=[{"name": i, "id": i, "deletable": False, "selectable": True} for i in df.columns]
    # Reset selected row to first row when filter setting changes
    selected_rows = [0]
    
    return (data, columns, selected_rows)

#Histogram Chart, populated by filter selection or if no filter is selected the chart will populate the data on the current table
@app.callback(
    Output('graph-id', "children"),
    [Input('datatable-id', "derived_viewport_data"),
     #Input('filter-type', 'value')
    ])
def update_graphs(Data):
    df = pd.DataFrame.from_records(Data)
    
    return [
        dcc.Graph(            
            figure = px.histogram(df, x='breed')
        )    
    ]

# Map- populates geolocation of selected animal, if no animal selected the first animal on the current data table will auto select
@app.callback(
    Output('map-id', "children"),
    [Input('datatable-id', "derived_viewport_data"),
     Input('datatable-id', 'derived_viewport_selected_rows')])
def update_map(Data, row_ids):
    dff = pd.DataFrame.from_records(Data)
    # Sets first num in row_ids array to the last selected row ID
    row_ids[0] = row_ids[len(row_ids) - 1]
    return [
        # gets lattitude and longitude of last selected row
        dl.Map(style={'width': '1000px', 'height': '500px'}, center=[dff.iloc[row_ids[0],13],dff.iloc[row_ids[0],14]], zoom=10, children=[
            dl.TileLayer(id="base-layer-id"),
            # Marker with tool tip and popup
            dl.Marker(position=[dff.iloc[row_ids[0],13],dff.iloc[row_ids[0],14]], children=[
                # display breed of animal
                dl.Tooltip(dff.iloc[row_ids[0],4]),
                dl.Popup([
                    html.H1("Name:"),
                    # display animal's name
                    html.P(dff.iloc[row_ids[0],9])
                ])
            ])
        ])
    ]

app.run_server(debug=True)

SUCCESS - accessed database
      rec_num age_upon_outcome animal_id animal_type  \
0           2           1 year   A725717         Cat
1           1          3 years   A746874         Cat
2           3          2 years   A716330         Dog
3           9          3 years   A720214         Dog
4          10         3 months   A664290         Cat
...       ...              ...       ...         ...
9995     9983          6 years   A680988         Cat
9996     9985          4 years   A712011         Dog
9997     9998         2 months   A697165         Dog
9998     9999         2 months   A665304         Dog
9999    10000          4 weeks   A728994       Other

                                         breed              color  \
0                       Domestic Shorthair Mix       Silver Tabby
1                       Domestic Shorthair Mix        Black/White
2                      Chihuahua Shorthair Mix        Brown/White
3                       Labrador Retriever Mix          Red/White
4                       Domestic Shorthair Mix             Tortie
...                                        ...                ...
9995                    Domestic Shorthair Mix  Brown Tabby/White
9996  Jack Russell Terrier/Chihuahua Shorthair           Tricolor
9997        Labrador Retriever/Anatol Shepherd        White/Black
9998        Newfoundland/Australian Cattle Dog        Black/White
9999                                       Bat                Red

     date_of_birth             datetime            monthyear      name  \
0       2015-05-02  2016-05-06 10:49:00  2016-05-06T10:49:00
1       2014-04-10  2017-04-11 09:00:00  2017-04-11T09:00:00
2       2013-11-18  2015-12-28 18:43:00  2015-12-28T18:43:00     Frank
3       2013-02-04  2016-02-11 12:41:00  2016-02-11T12:41:00  Blessing
4       2013-09-01  2013-12-08 14:58:00  2013-12-08T14:58:00   *Taylor
...            ...                  ...                  ...       ...
9995    2008-06-10  2014-06-12 19:12:00  2014-06-12T19:12:00
9996    2011-09-15  2015-09-19 12:33:00  2015-09-19T12:33:00     Daisy
9997    2015-02-18  2015-05-03 00:00:00  2015-05-03T00:00:00     *Zoey
9998    2013-08-16  2013-10-20 17:46:00  2013-10-20T17:46:00     Flynn
9999    2016-05-12  2016-06-12 12:48:00  2016-06-12T12:48:00

     outcome_subtype outcome_type sex_upon_outcome  location_lat  \
0               SCRP     Transfer    Spayed Female     30.652598
1               SCRP     Transfer    Neutered Male     30.506658
2                        Adoption    Neutered Male     30.759575
3                        Adoption    Spayed Female     30.387065
4                        Adoption    Spayed Female     30.758311
...              ...          ...              ...           ...
9995            SCRP     Transfer    Neutered Male     30.353110
9996                     Adoption    Spayed Female     30.754688
9997         Offsite     Adoption    Spayed Female     30.477896
9998                     Adoption    Neutered Male     30.382226
9999     Rabies Risk   Euthanasia          Unknown     30.666477

      location_long  age_upon_outcome_in_weeks
0        -97.741996                  52.921528
1        -97.340878                 156.767857
2        -97.552375                 110.111409
3        -97.368434                 157.504067
4        -97.618292                  14.089087
...             ...                        ...
9995     -97.606429                 313.400000
9996     -97.323500                 209.360417
9997     -97.356929                  10.571429
9998     -97.321557                   9.391468
9999     -97.403375                   4.504762

[10000 rows x 16 columns]
Dash app running on http://127.0.0.1:25259/